import QtQuick 2.15
//import QtQml 2.3

QtObject {
    readonly property string fa_trash                   : "\uf1f8"
    readonly property string fa_plus                    : "\uf067"
    readonly property string fa_minus                   : "\uf068"
    readonly property string fa_ellipsis_h              : "\uf141"
    readonly property string fa_pen_to_square           : "\uf044"
    readonly property string fa_gear                    : "\uf013"
    readonly property string fa_sliders                 : "\uf1de"
    readonly property string fa_arrow_left_to_line      : "\uf33e"
    readonly property string fa_arrow_right_to_line     : "\uf340"
    readonly property string fa_caret_right             : "\uf0da"
    readonly property string fa_caret_down              : "\uf0d7"
    readonly property string fa_caret_left              : "\uf0d9"
    readonly property string fa_undo_alt                : "\uf2ea"
    readonly property string fa_chevron_down            : "\uf078"
    readonly property string fa_chevron_right           : "\uf054"
    readonly property string fa_circle                  : "\uf111"
    readonly property string fa_circle_xmark            : "\uf057"
    readonly property string fa_xmark                   : "\uf00d"
    readonly property string fa_linux                   : "\uf17c"
    readonly property string fa_bell                    : "\uf0f3"
    readonly property string fa_circle_check            : "\uf058"
    readonly property string check                      : "\uf00c"
    readonly property string fa_face_sad_tear           : "\uf5b4"
    readonly property string fa_arrows_to_eye           : "\ue4bf"
    readonly property string fa_star                    : "\uf005"
    readonly property string fa_chevron_left            : "\uf053"
    readonly property string fa_link                    : "\uf0c1"
    readonly property string fa_list_ul                 : "\uf0ca"
    readonly property string fa_square_check            : "\uf14a"
    readonly property string fa_italic                  : "\uf033"
    readonly property string fa_strikethrough           : "\uf0cc"
    readonly property string fa_code                    : "\uf121"
    readonly property string fa_copy                    : "\uf0c5"
    readonly property string fa_link_slash              : "\uf127"
    readonly property string fa_bold                    : "\uf032"
    readonly property string fa_underline               : "\uf0cd"
    readonly property string fa_heading                 : "\uf1dc"
    readonly property string fa_grip_vertical           : "\uf58e"
    readonly property string fa_font                    : "\uf031"
    readonly property string fa_align_right             : "\uf038"
    readonly property string fa_align_center            : "\uf037"
    readonly property string fa_align_left              : "\uf036"
    readonly property string fa_image                   : "\uf03e"

    readonly property string mt_view_kanban             : "\ueb7f"
    readonly property string mt_article                 : "\uef42"
    readonly property string mt_globe                   : "\ue894"
    readonly property string mt_code                    : "\ue86f"
}
